---
title: "hw2_agr"
author: "Анастасия Костяницына"
output: html_document
---


### 1.1
```{r}
library(tidyverse)
library(mosaic)
 
df <- read_csv('https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/Stoneberry/hw2_binomial/hw2_binomial.csv')

binomial_test <- binom.test(x = df$k, n = df$n, p = df$prior)
binomial_test

```

### 1.2
```{r}
set.seed(42)
do(1000)*
  sum(sample(x = 1:0, 
             size = df$n, 
             prob = c(df$prior, 1-df$prior), 
             replace = TRUE)) ->
  simulations
simulations %>% 
  mutate(greater = sum >= df$k) %>% 
  count(greater)

```

### 1.3
```{r}

alpha_prior <-df$prior*df$n
beta_prior <-(1-df$prior)*df$n

alpha_data <- df$k
beta_data <- df$n - df$k

alpha_post <- alpha_prior + alpha_data
beta_post <- beta_prior + beta_data

alpha_post/(alpha_post+beta_post)

```

### 1.4
```{r}

alpha_prior <- 1
beta_prior <- 1

alpha_data <- df$k
beta_data <- df$n - df$k

alpha_post <- alpha_prior + alpha_data
beta_post <- beta_prior + beta_data

alpha_post/(alpha_post+beta_post)
```

### 1.5
```{r}
# 'Известно, что частотность слова __вставьте_слово__ - 0.4417361. Целью нашего исследования было проверить сколько раз оно встречается у носителя русского языка в повседневной речи. Запись респондента состояла из 161 слова, из которых __вставьте_слово__ встретилось 65 раз. Частотность для нашего носителя - с точки зрения Фринквентиткого подхода равна 0.4037267, а с точки зрения Байесовского подхода - 0.4227314. По результатам биномиального теста видно, что вероятность количества успехов статистически не отличается от ожидаемой вероятности, так как p-value = 0.3421, что доказывает и результаты, полученные на основе симуляции данных.'
```
