---
title: "hw2_agr"
author: "Анастасия Костяницына"
output: html_document
---


### 1.1
```{r}
library(bootstrap)
library(mosaic)
library(tidyverse)

df <- read_csv('https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/Stoneberry/hw3_binomial_ci/hw3_wodehouse.csv')

n_words <- df %>% group_by(chapter)%>% summarise(n =  n())

a <- df %>% 
  filter(word == 'сэр')

a1 <- a %>% group_by(chapter)%>% summarise(n =  n())

sir <- data_frame(chapters = a1$chapter, n = a1$n, n_words = n_words$n) %>%
  mutate(average = n/n_words)

sir %>% 
  summarise(g_mean = mean(average))

```
### 1.2
```{r}
set.seed(42)
df %>% 
  filter(word == "сэр") ->
  df_bs

sir_bs <- bootstrap(sir$average, nboot = 10000, theta = mean)$thetastar
sir_bs <- data_frame(means = sir_bs) 

sir_bs %>%
  summarise(mean = mean(means),
            q1 = quantile(means, 0.025),
            q2 = quantile(means, 0.975)) %>%
   mutate(interval = q2 - q1) -> sir_stats

sir_stats

```

### 1.3
```{r}

ci <- sir %>% 
  group_by(chapters) %>% 
  mutate(low_ci = binom.test(x = n, n = n_words, ci.method = "Clopper-Pearson")$conf.int[1],
         up_ci = binom.test(x = n, n = n_words, ci.method = "Clopper-Pearson")$conf.int[2],
         interval = up_ci - low_ci)

ci[which.max(ci$interval),]

```


### 1.4
```{r}

mu <- mean(sir$average)
var <- var(sir$average)
alpha0 <- ((1 - mu) / var - 1 / mu) * mu ^ 2
beta0 <- alpha0 * (1 / mu - 1)

sir %>% 
  mutate(alpha_post = n+alpha0,
         beta_post = n_words-n+beta0,
         average_post = alpha_post/(alpha_post+beta_post),
         cred_int_l = qbeta(.025, alpha_post, beta_post),
         cred_int_h = qbeta(.975, alpha_post, beta_post),
         interval = cred_int_h -  cred_int_l) ->
  posterior

posterior %>% 
  select(chapters, n_words, average, average_post) %>% 
  arrange(n_words)

posterior[which.max(posterior$interval),]

```

### 1.5
```{r}
ci[which.min(ci$interval),]

```


### 1.6
```{r}
posterior[which.min(posterior$interval),]
```


### 1.7
``` {r}
ci %>% 
  ggplot(aes(chapters, average, ymin = low_ci, ymax = up_ci))+
  geom_errorbar()+
  geom_point()+
  coord_flip()+
  theme_bw()+
  geom_errorbar(aes(posterior$chapters, posterior$average_post, ymin = posterior$cred_int_l, ymax = posterior$cred_int_h, color = 'red'))+
  geom_point(aes(posterior$chapters, posterior$average_post, color = 'red'))

# Как видно на графике, разница между оценками среднего и доверительных интервалов количества употреблений слова “сэр” во всех главах романа не сильно отличается. Наибольшее различие между средними наблюдается у Главы 6 (0.0008), в то время как для Главы 8 они практически совпадают. Видно, что confidence interval чуть больше, чем credible interval.
```
